"""Combine the two validated matrix-buffer copies without changing their values."""

def optimize_matrixpaircopy(out, port, override, replace):
    p = out / 'managed/Foster/Material.cs'
    s = p.read_text()
    a = '    protected struct MatrixUniformCache'
    s = replace(s, a, '    [System.Runtime.InteropServices.DllImport("FosterPlatform", CallingConvention=System.Runtime.InteropServices.CallingConvention.Cdecl)]\n    private static extern unsafe void FosterMaterialCopyMatrixPair(float* destinationA,float* sourceA,int countA,float* destinationB,float* sourceB,int countB);\n    protected unsafe bool TrySetCachedMatrixPair(string nameA,in Matrix4x4 valueA,ref MatrixUniformCache cacheA,\n        string nameB,in Matrix4x4 valueB,ref MatrixUniformCache cacheB)\n    {\n        // A failed or stale binding takes the original sequential setter path,\n        // preserving exception type/message and the first setter\'s partial writes.\n        if(cacheA.Epoch!=uniformEpoch || cacheB.Epoch!=uniformEpoch || cacheA.Name!=nameA || cacheB.Name!=nameB)return false;\n        if(cacheA.Present && (cacheA.Length<0 || (uint)cacheA.Start>(uint)floatBuffer.Length || Math.Min(16,cacheA.Length)>floatBuffer.Length-cacheA.Start))return false;\n        if(cacheB.Present && (cacheB.Length<0 || (uint)cacheB.Start>(uint)floatBuffer.Length || Math.Min(16,cacheB.Length)>floatBuffer.Length-cacheB.Start))return false;\n        fixed(float* destination=floatBuffer)\n        fixed(Matrix4x4* sourceA=&valueA)\n        fixed(Matrix4x4* sourceB=&valueB)\n            FosterMaterialCopyMatrixPair(destination+cacheA.Start,(float*)sourceA,cacheA.Present?Math.Min(16,cacheA.Length):0,\n                destination+cacheB.Start,(float*)sourceB,cacheB.Present?Math.Min(16,cacheB.Length):0);\n        return true;\n    }\n\n' + a)
    p.write_text(s)
    override('Graphics/Materials.cs', [('public string Name = string.Empty;', 'public string Name = string.Empty;\n    public void SetModelAndMVP(in Matrix modelValue,in Matrix mvpValue)\n    {\n        if(TrySetCachedMatrixPair("u_model",modelValue,ref modelBinding,"u_mvp",mvpValue,ref mvpBinding))\n        { model=modelValue;matrix=mvpValue; }\n        else { Model=modelValue;MVP=mvpValue; }\n    }')])
    override('Graphics/RenderState.cs', [('mat.Model = matrices.Model;\n        mat.MVP = matrices.MVP;', 'mat.SetModelAndMVP(matrices.Model, matrices.MVP);')])
    (out / 'foster/switch_matrix_pair_copy.c').write_text((port / 'optimizations/matrix_pair_copy.c').read_text())
